### ISSUE TITLE
Questions about PR #108

### ISSUE THREAD

**Issue by rainlinWW** [facebook/OpenBIC#112]
Hi @Yi-Shum 

In PR #108 , is there any issue about malloc ipmi_msg so you have to modify it to declare directly instead?
From our point of view, malloc big size variable like ipmi_msg can reduce memory usage in thread stack, which means we can reduce size of all threads calling this function.

Also, for events that requires delay, suggest using k_work instead of creating extra thread and occupy kernel memory.

**Comment by Yi-Shum** [comment]
Hi @rainlinWW,

Thanks for your suggestion.

We directly declare ipmi_msg to avoid memory leaks, because threads proc_fail_thread_handler and CatErr_thread_handler may be aborted.

We will modify these two thread to use the timer instead of thread, and restore to dynamic allocation ipmi_msg.

Thanks,
Yi-Shum

**Comment by GoldenBug** [comment]
Hi @Yi-Shum,

Has this change been made and merged yet or is it still ongoing?

**Comment by Yi-Shum** [comment]
fby3.5: cl: Modify FRB3 and CATERR event log (#117) solve this issue.

**Comment by Yi-Shum** [comment]
Hi @GoldenBug,

It has been merged.

Thanks,
Yi-Shum

**Comment by rainlinWW** [comment]
Hi @GoldenBug 

Both of my concerns are fixed.
Please help to close this issue if no further questions.

Thanks,
Rain
